services:
  app:
    build:
      context: reservationapi/
    volumes:
      - ./reservationapi/src:/src
    command:
      - "sh"
      - "-c"
      - |
        pip install debugpy -t /tmp \
        && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 \
        -m uvicorn src.main:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
      - 5678:5678
    environment:
      - TZ=Europe/Warsaw
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASSWORD=pass
    depends_on:
      - db
    networks:
      - backend
    container_name: app

  db:
    image: postgres:17.0-alpine3.20
    environment:
      - TZ=Europe/Warsaw
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
    ports:
      - "5432:5432"
    networks:
      - backend
    container_name: db

networks:
  backend: